name: Build docker image

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # foo:
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 30
  #   steps:
  #     - name: Build docker image
  #       run: |
  #         docker build -t test .
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
