name: Tag as release 

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to release'
        required: true

permissions:
  contents: read

env:
  image_name: xaynetci/yellow
  release_tag: v1

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Set image tag
        run: |
          echo "image_tag=${github.event.inputs.image_tag}" >> $GITHUB_ENV

      - name: docker pull
        run: |
          docker pull "${{ env.image_name }}:${{ env.image_tag }}"
      
      - name: tag as release
        run: |
          docker tag "${{ env.image_name }}:${{ env.image_tag }}" "${{ env.image_name }}:${{ env.release_tag }}"

      - name: docker push
        run: |
          docker push "${{ env.image_name }}:${{ env.release_tag }}"
