name: Tag as release 

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  image_name: xaynetci/yellow

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Determine image tag
        run: |
          IMAGE_TAG="$(git rev-parse --short "$GITHUB_SHA")"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: docker pull
        run: |
          docker pull "${{ env.image_name }}:${{ env.image_tag }}"
      
      - name: tag as release
        run: |
          docker tag "${{ env.image_name }}:${{ env.image_tag }}" "${{ env.image_name }}:release"

      - name: docker push
        run: |
          docker push "${{ env.image_name }}:release"
